name: automatic_deploy
on: 
  push:
    branches: [automatic_deployment]

jobs:
  configure_page:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir _site/
          mv Website/index.html _site/index.html
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
